### ISSUE TITLE
gotemplating: variable storage/scope outside of an "if" 

### ISSUE THREAD

**Issue by Boran** [nginx-proxy/docker-gen#106]
I'm hacking the template example in nginx-proxy for my own needs , e.g for (mixed) http/s.

First question is that I see some pull requests for various nginx examples, but they are not committed? Could one put them in either the nginx-proxy or docker-gen repos?

Now to the real question... I'd like to iterate through many backed IP/port combinations, store the result, and then check that the result is actually usable before creating an nginx "server" line. This is to avoid invalid nginx configurations due to unexpected containers.
Something like the following logic.

```
  {{ range $container := $containers }}
        {{ $addrLen := len $container.Addresses }}
        {{ $serverport := 80 }} {{/* default backend */}}
        {{ $serverip := "NONE" }} {{/* default backend */}}
        {{ if eq $addrLen 1 }}
                {{ with $address := index $container.Addresses 0 }}
                   {{ $serverport := $address.Port }};
                   {{ $serverip := $address.IP }};
                {{ end }}
        {{ else if $container.Env.VIRTUAL_PORT }}
                {{ range $address := .Addresses }}
                   {{ if eq $address.Port $container.Env.VIRTUAL_PORT }}
                        {{ $serverport := $address.Port }};
                        {{ $serverip := $address.IP }};
                   {{ end }}
                {{ end }}
        {{ else }}
                {{ range $address := $container.Addresses }}
                        {{ if eq $address.Port "80" }}
                                {{ $serverport := $address.Port }};
                                {{ $serverip := $address.IP }};
                        {{ end }}
                {{ end }}
        {{ end }}
        # do we have a valid config?
        {{ if eq $serverip "NONE" }}
          # unable to find a backend {{ $serverip }} {{ $serverport }}
        {{ else }}
          server {{ $serverip }}:{{ $serverport }};
        {{ end }}
```

The problem is that variables are only scoped within the if -then-else-end, so by the time it gets to "do we have a valid config" above the values set for $serverip  are lost, and we only see the default.

I'm new to this go templating, is there an alternative way to do this or have I missed something?

**Comment by pini-gh** [comment]
A bit late, but anyway...

The `:=` operator declares a new local scope variable, masking any previous declaration with the same name.
Use the `=` operator inside the `if` blocks to change the value of your previously declared `$serverip` variable:
```
        {{ $serverip := "NONE" }} {{/* default backend */}}
        {{ if eq $addrLen 1 }}
                   ...
                   {{ $serverip = $address.IP }};
                   ...
        {{ end }}
```

**Comment by josegonzalez** [comment]
This can probably be closed :)
