### ISSUE TITLE
Add Links structure

### ISSUE THREAD

**Issue by ocorbier** [nginx-proxy/docker-gen#132]
Hi, i would like use the "--link" parameter(s) of a container in the emit structure. Something like the Env Field of RuntimeContainer.
thank's in advance

**Comment by jwilder** [comment]
Not sure if this is possible.  I think `--links` just sets up hosts file entries and I don't think those are exposed through the docker API directly.  It might be possible to use the `docker cp` command to get the contents of `/etc/hosts` on a container though.

**Comment by buchdag** [comment]
The `--link` flag [is a legacy feature and considered depreciated](https://docs.docker.com/network/links/).
