### ISSUE TITLE
Several undefined errors on build

### ISSUE THREAD

**Issue by mldulaney** [nginx-proxy/docker-gen#167]
As I mentioned, I am working on packaging for Fedora.  Build is failing with the following errors:

../../BUILDROOT/docker-gen-0.7.0-0.fc25.i386/usr/share/gocode/src/github.com/jwilder/docker-gen/generator.go:408: container.NetworkSettings.Networks undefined (type *docker.NetworkSettings has no field or method Networks)
../../BUILDROOT/docker-gen-0.7.0-0.fc25.i386/usr/share/gocode/src/github.com/jwilder/docker-gen/generator.go:441: v.Name undefined (type docker.Mount has no field or method Name)
../../BUILDROOT/docker-gen-0.7.0-0.fc25.i386/usr/share/gocode/src/github.com/jwilder/docker-gen/generator.go:444: v.Driver undefined (type docker.Mount has no field or method Driver)

Am I missing a dependency somewhere?

**Comment by jwilder** [comment]
Are you getting this error even after following the instructions here? https://github.com/jwilder/docker-gen#development

**Comment by buchdag** [comment]
Closing inactive issue.
