### ISSUE TITLE
Question about docker-gen nginx config generation and SSL

### ISSUE THREAD

**Issue by ghost** [nginx-proxy/docker-gen#168]
I'm having a problem using docker-gen and nginx reverse proxy with a secure backend. docker-gen and nginx are running in separate containers. My question is whether or not the docker-gen generated default.conf file should have a line with "listen 443" and a proxy_pass line with "https://servername"?  There are no such lines in the generated config file.

I am starting my application containers with:

/usr/bin/docker run -d --name $name \
  -e VIRTUAL_PROTO=https \
  -e VIRTUAL_HOST=$client \
  -e VIRTUAL_PORT=27292 \
  -p 27292 \
  -v /etc/timezone:/etc/timezone\
   sdsi/unform9-docker:v1

and nginx:

/usr/bin/docker run -d -t --name proxy  \
  -p 80:80 -p 443:443  \
  -v /etc/apache2/.htpasswd:/etc/nginx/htpasswd \
  -v /var/lib/sdsi/certs:/etc/nginx/certs \
  -v /var/lib/sdsi/nginx/conf.d:/etc/nginx/conf.d \
  sdsi/nginx:v1

and docker-gen:

/usr/bin/docker run -d --name docgen --volumes-from proxy \
   -v /var/run/docker.sock:/tmp/docker.sock:ro \
   -v /var/lib/sdsi/docgen/templates:/etc/docker-gen/templates \
   -t jwilder/docker-gen -notify-sighup proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

The certificates are letsencrypt multiple domain certificates. I have tried the various certificate naming schemes, i.e. vhost.domain.net.crt, vhost.domain.net.key and domain.net.crt, domain.net.key and shared.crt, shared.key with the CERT_NAME=shared env var defined in the container run command line. In addition I've tried just leaving the filenames as provided by letsencrypt.

The error I get (using chrome) is: "This site can't be reached" and using curl I get the error:
- Connected to demo.unform.net (96.81.167.53) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSLv3, TLS handshake, Client hello (1):
- Unknown SSL protocol error in connection to demo.domain.net:443
- Closing connection 0
  curl: (35) Unknown SSL protocol error in connection to demo.domain.net:443

The curl command line I am using is:

curl -v  -k --basic -u user:passwd https://demo.domain.net

Any help would be greatly appreciated. If I can provide any further information please let me know.

Best Regards,

Daryl Williams

**Comment by ekkis** [comment]
I have a similar question.  I'm using the `nginx-proxy` docker image and the configuration file I see docker-gen create makes no reference to SSL support.  no certs listed.  here's a fragment:

```
upstream sandbox.graph.speakr.com {
                        # sandbox-app
                        server 172.18.0.2:8000;
}
server {
        gzip_types text/plain text/css application/json application/x-javascript
 text/xml application/xml application/xml+rss text/javascript;
        server_name sandbox.graph.speakr.com;
        proxy_buffering off;
        error_log /proc/self/fd/2;
        access_log /proc/self/fd/1;
        location / {
                proxy_pass http://sandbox.graph.speakr.com;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                # HTTP 1.1 support
                proxy_http_version 1.1;
                proxy_set_header Connection "";
        }
}
```

and if I look in the certs directory I see them:

```
$ docker exec -it  nginx-gen ls -alF /etc/nginx/certs
total 16
drwxrwxr-x    3 1000     1000          4096 Apr 26 20:23 ./
drwxr-xr-x    5 root     root          4096 Apr 26 20:22 ../
-rw-r--r--    1 root     root           424 Apr 26 06:04 dhparam.pem
drwxr-xr-x    2 root     root          4096 Apr 26 20:23 sandbox.graph.speakr.com/
lrwxrwxrwx    1 root     root            36 Apr 26 20:23 sandbox.graph.speakr.com.chain.pem -> ./sandbox.graph.speakr.com/chain.pem
lrwxrwxrwx    1 root     root            40 Apr 26 20:23 sandbox.graph.speakr.com.crt -> ./sandbox.graph.speakr.com/fullchain.pem
lrwxrwxrwx    1 root     root            13 Apr 26 20:23 sandbox.graph.speakr.com.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx    1 root     root            34 Apr 26 20:23 sandbox.graph.speakr.com.key -> ./sandbox.graph.speakr.com/key.pem
```

so what else do I need to make it work? at present nginx serves the sites on port 80 without issue but requests on https are denied with ERR_CONNECTION_REFUSED

**Comment by ekkis** [comment]
ok, I figured out my problem.  I had some nginx.tmpl file that didn't have support for SSL.  this fixed the problem: 

`curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > /path/to/nginx.tmpl`

**Comment by buchdag** [comment]
This repo should no longer handle issues or discussions related to nginx-proxy / the nginx-proxy template, unless there is something we need to change / fix in docker-gen in order to allow a change / fix in nginx-proxy.
