### ISSUE TITLE
Use docker-gen with SSL Certificate

### ISSUE THREAD

**Issue by lukasoppermann** [nginx-proxy/docker-gen#216]
Hey @jwilder,

can you maybe extend the readme a bit to let me know how to setup ssl? I am at a loss here.

My setup is as follows:

> - proxy: nginx
> - docker-gen
> - app1-server: nginx
> - app2-server: nginx

I am creating the certificate via an nginx and would like to store them on a docker volume.
However, now that I have the certificates and everything how do I make my pages load via https?

Please keep in mind, that with multiple domains, the certs are stored in separate directories, e.g.:

ssl_certificate /etc/letsencrypt/live/app1.test.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/app2.test.com/privkey.pem;

cc: @wader

**Comment by wader** [comment]
Hi, it should be automatic but it looks like your certificates are not named the way the default nginx-proxy template expects. Have you read https://github.com/jwilder/nginx-proxy#ssl-support for how the files should be named? you could of course modify the template to follow your scheme.

**Comment by lukasoppermann** [comment]
Hmm, so I added the lines from above to the nginx file:

```shell
# Is replace this:
ssl_certificate /etc/nginx/certs/default.crt;
ssl_certificate_key /etc/nginx/certs/default.key;

# with this:
ssl_certificate /etc/letsencrypt/live/{{ $host }}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/{{ $host }}/privkey.pem;
```

This does not count as `modify the template`? They are both `.pem` files though, this is what is created by lets encrypt.

**Comment by wader** [comment]
Oh just noticed that this issue was for docker-gen, got confused. What template are you using? a modified version of the nginx-proxy template?

**Comment by lukasoppermann** [comment]
@wader Yes, I am using a modified version of the [nginx-proxy template](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl) although the only thing I changed so far is the above mentioned file paths as well as the path to the `dhparam.pem`.
