### ISSUE TITLE
Add ability to just restart container

### ISSUE THREAD

**Issue by stevenmyhre** [nginx-proxy/docker-gen#251]
I am using this, the letsencrypt companion and nginx as a reverse proxy and it is working great to auto-renew my ssl certificates. Now, I am trying to use these same certificates for mongodb SSL/TLS replica set encryption.  Mongodb container does not accept SIGHUP to reload configuration (and therefore the certs).

It would be nice if there were an option to **restart** a container by name, similar to the SIGHUP option. This way any time there was a new certificate the mongodb container would be restarted and the certs reloaded.

If you have any suggestions (wrapper around mongodb to capture SIGHUP???) let me know.

I noticed the ```fsouza/go-dockerclient```  library you reference also has ```RestartContainer``` as part of the API.

**Comment by buchdag** [comment]
This feature has already been added:

> ```
> -notify-signal signal
>       signal to send to the -notify-container. -1 to call docker restart. Defaults to 1 aka. HUP.
>       All available signals available on the dockerclient
>       https://github.com/fsouza/go-dockerclient/blob/01804dec8a84d0a77e63611f2b62d33e9bb2b64a/signal.go
> ```

`-notify-signal -1` will restart containers.
