### ISSUE TITLE
Allow only internal networks

### ISSUE THREAD

**Issue by kaosmonk** [nginx-proxy/docker-gen#258]
Hello,

I'd like to have some containers exposed only to internal networks as explained in [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy#internet-vs-local-network-access) docs but since I am using separate containers in my setup - official nginx and docker-gen images - I'm not sure how to do exactly the same. Should I edit the _nginx.tmpl_ or am I missing some existing options?

Thanks!

**Comment by tomfun** [comment]
@kaosmonk as I understand, it is already done. I use almost official nginx.tmpl (with one important fix) and official nginx and docker-gen docker images. My APIs inside one virtual network with nginx, but it is internal docker network.

**Comment by returntrip** [comment]
@kaosmonk just noticed this open issue. To make `NETWORK_ACCESS=internal` on `docker-gen` do the following:

Manually mount  [network_internal.conf](https://github.com/jwilder/nginx-proxy/blob/3ef600a3b56105fa4ac343ef6d10b2c52818fec0/network_internal.conf) in `/etc/nginx/network_internal.conf ` and use the [nginx-proxy](https://github.com/jwilder/nginx-proxy/blob/226bfe158fc90b057cec727a7dd36b7a078cbe49/nginx.tmpl) from https://github.com/jwilder/nginx-proxy

**Comment by kaosmonk** [comment]
Thanks a lot!

**Comment by jlegido** [comment]
Jus for the records, with official [nginx](https://hub.docker.com/_/nginx) image it works as expected, mounting:

`
-v /path/to/network_internal.conf:/etc/nginx/network_internal.conf
`

I tested it with 3 containers (official nginx, nginx-gen and nginx-letsencryptcompanion)

**Comment by hacker-h** [comment]
I had a similar use case:
I needed to proxy containers which are only connected to an internal network (to deny egress traffic),
therefore they cannot expose ports and require some template configuration to be proxiable.
I described the issue and my solution in the google group:
https://groups.google.com/forum/#!topic/nginx-proxy/YL5GypqStOA
