### ISSUE TITLE
CurrentContainerID not fetched

### ISSUE THREAD

**Issue by kaiokenx10** [nginx-proxy/docker-gen#284]
Hi,

I noticed that on the latest multicontainer docker env on AWS with ecs agent in version `1.17.2` the container id is empty and this ends up in empty upstream blocks for my nginx config in nginx-proxy container which uses docker-gen. Starting from ecs agent `1.16` the letsencrypt comapanion was not able to get its own container id, so it started supporting the `ECS_CONTAINER_METADATA_FILE` variable which holds the containerID in very simply way (it is a JSON file). My question is why similar approach can not be used here instead of attempts of doing the regexp matching on the `/proc/self/cgroup`? We could simply check if `ECS_CONTAINER_METADATA_FILE` is defined and use it for fetching "ContainerID".

**Comment by jwilder** [comment]
Sure. We could do that.

**Comment by buchdag** [comment]
This should have been fixed by #336 and #345
