### ISSUE TITLE
Version 0.7.4 missing on Docker hub

### ISSUE THREAD

**Issue by mbrodala** [nginx-proxy/docker-gen#289]
There is a Git tag `0.7.4` but there is no such Docker image tag on the Docker hub. Can you please push that image version?

**Comment by jgraglia** [comment]
see #281

**Comment by vsalvino** [comment]
FYI I made a fork, which is updated to the latest code in this repo, and also built with go 1.11 to get all of those new templating features. It has been working great for me.

https://github.com/coderedcorp/docker-gen and available on docker hub under `coderedcorp/docker-gen`

**Comment by buchdag** [comment]
This was fixed by #347
