### ISSUE TITLE
add '=' operand support

### ISSUE THREAD

**Issue by zam5607822** [nginx-proxy/docker-gen#299]
when i write these in template file:
`$is_https = "true"`

docker-gen complained:

> Unable to parse template: template: nginx.tmpl:188: unexpected "=" in operand

it seems that template engine does not support '=' operand,but text/template in go package does support,see [Package template](https://golang.org/pkg/text/template/#hdr-Variables) which says:
> Variables previously declared can also be assigned, using the syntax:
`$variable = pipeline`

so what's the problem? is the version of template which docker-gen used too old?

**Comment by vsalvino** [comment]
I had the same issue. Discovered that feature was added in go 1.11. The docker-gen releases are all built with go 1.9.

I created a fork and got it working with go 1.11 https://github.com/coderedcorp/docker-gen

Also available on docker hub under `coderedcorp/docker-gen`

**Comment by blazej-pachut-gforces** [comment]
👍 
I've faced same issue while trying to elegantly fix https://github.com/jwilder/nginx-proxy/issues/1132 😞

**Comment by tjhiggins** [comment]
+1

**Comment by buchdag** [comment]
Non longer relevant, docker-gen is built with up-to-date version of Go.
