### ISSUE TITLE
Sighup from docker-gen does not restart nginx-proxy container

### ISSUE THREAD

**Issue by MikaelElkiaer** [nginx-proxy/docker-gen#312]
I am having an issue with getting docker-gen to restart nginx-proxy on changes.
I am running the nginx proxy (linuxserver/nginx:latest) and docker-gen containers seperately on a server running Unraid OS.

If I start the nginx-proxy container everything works as expected.
However, if I change some meta, e.g. set VIRTUAL_HOST on a container, nginx-proxy fails to reload via sighup.

I see the following log for nginx-proxy:
```
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by kcindric** [comment]
Did you find the solution for this problem?

**Comment by MikaelElkiaer** [comment]
> Did you find the solution for this problem?

Nope, I am now using [Traefik](https://containo.us/traefik/).

**Comment by sgabe** [comment]
The [linuxserver/nginx](https://hub.docker.com/r/linuxserver/nginx/) container is based on [s6-overlay](https://github.com/just-containers/s6-overlay), which seems to be incompatible to be reloaded via `SIGHUP`, see e.g. https://github.com/just-containers/s6-overlay/issues/173 for more information. Note that `docker-gen` still works fine using the official [nginx](https://hub.docker.com/_/nginx) container.
