### ISSUE TITLE
Include existing ARM64 build in binary releases 

### ISSUE THREAD

**Issue by MattJeanes** [nginx-proxy/docker-gen#325]
The existing Makefile already builds ARM64 binaries for both Linux and Alpine Linux but the binaries are not included in the releases for some reason. Can we please include them?

I have manually built the Linux/ARM64 from master and I use it on a Raspberry Pi 3 using Ubuntu ARM64 and it appears to work just fine.

**Comment by TheDuckMann** [comment]
Dear MattJeanes,

I have a similar problem, but I am new to docker.
I wanted to use the existing [ARMhf](https://github.com/jwilder/docker-gen/releases/download/0.7.4/docker-gen-alpine-linux-armhf-0.7.4.tar.gz) on docker-gen for my Raspberry-Pi. I can't figure out how to use this. I already loaded and extracted the file from github, but i don't even know what I downloaded. Is it already an Image? What to do next? I want to use this in my docker-compose.yml but all I get are errors.

Could you maybe give me a hint or even tell me how to figure this out?
Thanks in advance!

**Comment by MattJeanes** [comment]
@TheDuckMann so once you extract the .tar.gz you just get a file called 'docker-gen' which can be marked executable with `chmod +x docker-gen` and then ran on the command line, it is not something you would call from a docker-compose file as such. Check out the readme of this project for how to use the application once you have it ready to go.

**Comment by TheDuckMann** [comment]
@MattJeanes thanks for your fast reply! Do you see any possibility to make the ARMhf run with/in a docker-compose or do I have to use an image which is on the docker hub? For Example this: [btcpayserver/docker-gen](https://hub.docker.com/r/btcpayserver/docker-gen)

**Comment by buchdag** [comment]
The binaries for `arm64` are now included with the releases.
