### ISSUE TITLE
$CurrentContainer is null

### ISSUE THREAD

**Issue by multicast** [nginx-proxy/docker-gen#355]
After a while I updated manually to `:latest` image from docker hub and all my containers ended up with upstream `server 127.0.0.1 down;`.

I copied `nginx.tmpl`, and after a while I found out `{{ $CurrentContainer := where $ "ID" .Docker.CurrentContainerID | first }}` returns `null`, so this [range](https://github.com/nginx-proxy/nginx-proxy/blob/4e3e518936d27d22e5e5e5552d41097d11bb727c/nginx.tmpl#L177) can never set `$server_found` to true.

Change from `$CurrentContainer.Networks` to `$container.Networks` ([from outer range](https://github.com/nginx-proxy/nginx-proxy/blob/4e3e518936d27d22e5e5e5552d41097d11bb727c/nginx.tmpl#L163)) solved the problem.

I am running Debian Bullseye (daily dist-upgraded until Bullseye is stable), and docker-ce vevrsion 5:20.10.7\~3-0\~debian-bullseye from docker.com (i.e. not debian-packaged docker).

Can somebody confirm this behavior? I can make pull request.

**Comment by buchdag** [comment]
Removing the custom `hostname` (proxy) and using a container name instead might be a quick fix.

**Comment by multicast** [comment]
Removing the custom hostname fixed the problem, thanks.

**Comment by buchdag** [comment]
@multicast I pushed a version of **nginx-proxy** built with a patched **docker-gen**, can you tell me if it works for you even with the custom hostname ?

```console
docker pull nginxproxy/nginx-proxy:dg355
```

**Comment by multicast** [comment]
Yes, I was checking :latest an hour after you merged, but still had to change the hostname.
The `containers/` prefix in the regex works when using custom hostname, awesome.

**Comment by buchdag** [comment]
@multicast the fix is now available in `nginxproxy/nginx-proxy:latest`
