### ISSUE TITLE
Apple M1 Processor not supported linux/arm64/v8

### ISSUE THREAD

**Issue by duttonw** [nginx-proxy/docker-gen#385]
This does not work with latest M1 Processors. linux/arm64/v8 
used via
https://github.com/amazeeio/docker-haproxy/blob/master/Dockerfile 

https://github.com/amazeeio/docker-haproxy/issues/11

**Comment by buchdag** [comment]
Hi, could you provide more informations about the issues you're experiencing with docker-gen on Apple M1 processors ?

**Comment by duttonw** [comment]
Ok, more digging into the downstream amazeeio/docker-haproxy#11 they are not swapping from amd64 to arm64 on their image builds.

I've got a workaround in place which gets me over the line, there is nothing wrong with docker-gen. :)
