### ISSUE TITLE
You need to add the Health.State property for the container

### ISSUE THREAD

**Issue by budarin** [nginx-proxy/docker-gen#434]
When the service is started, the readiness of the service for operation is checked for some time. 
During this time, the service is not ready to accept requests yet, but now the situation is such that we believe that it is already ready and requests that the service cannot serve are pouring in

It is necessary to distinguish between the Health.Status state in order to understand that the server may already be added to the upstream

And also in a situation when the service is overloaded and health check tells us that the service is not healthy - we could exclude it from the upstrem until it becomes operational again

**Comment by free6k** [comment]
I created pr https://github.com/nginx-proxy/docker-gen/pull/442, can check?

**Comment by buchdag** [comment]
Implemented by #442
