### ISSUE TITLE
'dict' operator and associated 'set' function returns 'map[string]interface {}' type instead of 'map[string]string'

### ISSUE THREAD

**Issue by pini-gh** [nginx-proxy/docker-gen#481]
This snippet:
```
{{ typeOf (dict "foo" "bar") }}
```
Produces the following output:
```
map[string]interface {}
```
instead of:
```
map[string]string
```

The same goes for the `set` function. Then it is impossible to set a string value inside an existing map:
```
2023/01/08 17:18:00 Template error: template: nginx.tmpl:285:17: executing "nginx.tmpl" at <$env>: wrong type for value; expected map[string]interface {}; got map[string]string

```

**Comment by buchdag** [comment]
Hi @pini-gh. I believe this might be because we're using [Sprig](https://masterminds.github.io/sprig/dicts.html).

> ### A Note on Dict Internals
> A `dict` is implemented in Go as a `map[string]interface{}`. Go developers can pass `map[string]interface{}` values into the context to make them available to templates as `dict`s.
